spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orderdb
    username: orderuser
    password: orderpass
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  
  data:
    redis:
      host: redis
      port: 6379
  
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin

logging:
  level:
    com.example.orderapi: INFO
    org.springframework.security: WARN
    org.springframework.jms: WARN
  file:
    name: /app/logs/order-api.log
